
const options = {};


options.option1 = [

	"Smirnoff",
	"Absolut",
	"Grey Goose",
	"Ketel One",
	"Deep Eddy Lemon",
	"Deep Eddy Ruby",
	"Belvedere",
	"New Amsterdam",
	"Tito's",

]

options.option2 = [

	"Canadian Club",
	"Knob Creek",
	"Four Roses",
	"Glenlivet",
	"Seagram's 7 Crown",
	"Woodford Reserve",
	"Johnnie Walker Black Label",
	"Johnnie Walker Red Label",
	"Evan Williams",
	"Bulleit",
	"Wild Turkey",
	"Maker's Mark",
	"Jameson",
	"Jim Beam",
	"Jack Daniel's",
	"Fireball",
	"Crown Royal",
	"Buffalo Trace",
	"Macallan",
	"Dewar's",

]

options.option3 = [

	"Jose Cuervo",
	"Casamigos Reposado",
	"Casamigos Anejo",
	"Herradura",
	"Clase Azul",
	"Patron",
	"Don Julio",
	"Don Julio 1942",
	"Milagro",
	"Lalo",

]

options.option4 = [

	"Bacardi",
	"Captain Morgan",
	"McDowell's",
	"Malibu",

]

options.option5= [

	"Bombay Sapphire",
	"Tanqueray",
	"Hendrick's",
	"Empress",
	"The Botanist",
	"Beefeater",

]

options.option6 = [

	"Milk",
	"Motor Oil",
	"Cyanide",
	"Dish Soap",
	"Hydrogen Peroxide",
	"Marinara",
	"Rain Water",
	"Apple Juice",
	"Salsa",
	"Queso",
	"Tomato Soup",
	"Chicken Broth",
	"Yogurt",
	"Toilet Cleaner",
	"Fabric Softener",
	"Pickle Juice",
	"Water",
	"Formaldehyde",
	"Paint",
	"Gasoline",
	"Melted Butter",
	"Bacon Grease",
	"Wet Cement",
	"Balsamic vinaigrette",
	"Mouthwash",
	"Miller Lite",
	"Bud Lite",
	"Liquid Metal",
	"Mountain Dew",
	"Salt Water",
	""

]

const mixers = [

	"Soda",
	"Tonic ",
	"Ginger ale",
	"Coke",
	"Sprite",
	"Orange juice",
	"Cranberry",
	"Grapefruit",
	"Club soda",
	"7-Up",
	"Grenadine",
	"Water",
	"Topo-Chico"

]

const splash = [

	"cranberry juice",
	"pineapple juice",
	"grapefruit juice",
	"lime juice",
	"orange juice",
	"water",

]

const also = [

	"Triple Sec",
	"Cointreau",
	"Grand Marnier",
	"Blue Curacao",
	"Vermouth",
	"Aperol",

]

const prepared = [

	"On the rocks",
	"Neat",
	"Shaken",
	"In a martini glass",
	"Chilled",

]

const firstname = [

	"Alabama",
	"Alaska",
	"Arizona",
	"Arkansas",
	"California",
	"Colorado",
	"Connecticut",
	"Delaware",
	"Florida",
	"Georgia",
	"Hawaii",
	"Idaho",
	"Illinois",
	"Indiana",
	"Iowa",
	"Kansas",
	"Kentucky",
	"Louisiana",
	"Maine",
	"Maryland",
	"Massachusetts",
	"Michigan",
	"Minnesota",
	"Mississippi",
	"Missouri",
	"Montana",
	"Nebraska",
	"Nevada",
	"New Hampshire",
	"New Jersey",
	"New Mexico",
	"New York",
	"North Carolina",
	"North Dakota",
	"Ohio",
	"Oklahoma",
	"Oregon",
	"Pennsylvania",
	"Rhode Island",
	"South Carolina",
	"South Dakota",
	"Tennessee",
	"Texas",
	"Utah",
	"Vermont",
	"Virginia",
	"Washington",
	"West Virginia",
	"Wisconsin",
	"Wyoming",
	"American",
	"Chinese",
	"Indian",
	"Japanese",
	"Brazilian",
	"Russian",
	"Mexican",
	"Indonesian",
	"Pakistani",
	"Nigerian",
	"Bangladeshi",
	"Egyptian",
	"Vietnamese",
	"Filipino",
	"Turkish",
	"Iranian",
	"German",
	"South Korean",
	"French",
	"Italian",
	"British",
	"South African",
	"Spanish",
	"Ukrainian",
	"Thai",
	"Polish",
	"Canadian",
	"Malaysian",
	"Dutch",
	"Argentine",
	"Saudi Arabian",
	"Taiwanese",
	"Australian",
	"Kenyan",
	"Colombian",
	"Venezuelan",
	"Chilean",
	"Swedish",
	"Swiss",
	"Belgian",
	"Austrian",
	"Norwegian",
	"Danish",
	"Finnish",
	"Greek",
	"Hungarian",
	"Czech",
	"Portuguese",
	"Israeli",
	"Irish",
	"Downtown",
	"Uptown",
	"Sideways",
	"Cursed",
	"Toyota",
	"Ford",
	"Chevrolet",
	"Honda",
	"Volkswagen",
	"Nissan",
	"Schrodinger's",
	"New Orleans",
	"New York",
	"Los Angeles",
	"Dallas",
	"Cowboy",
	"Mafia",
	"Mob Boss",
	"Rotating",
	"Screaming",
	"Unintentional",
	"Homeless",
	"Accidental",
	"Malicious",
	"Lobster",
	"Marinated",
	"Instant",
	"Explosive",
	"Liver-punching",
	"Backwards",
	"Upside Down",
	"Painful",
	"Alcohol",
	"Adam Sandler",
	"Sourdough",
	"Wasteland",
	"Space",
	"Devil's",
	"Imperceptible",
	"Impossible",
	"Non-Euclidean",
	"Four Dimensional",
	"Wailing",
	"Long",
	"Short",
	"Wide",
	"Screwdriver",
	"Horrifying",
	"Honeymoon",
	"Heartfelt",
	"Toxic",
	"Quantum",
	"Classical",
	"Rustic",
	"Super",
	"Lackluster",
	"Fermented",
	"Incomplete",
	"Emergency",
	"Wimpy",
	"Thinking Man's",

]

const lastname = [

	"Twister",
	"Tourniquet",
	"Nipple-Twister",
	"Accident",
	"Explosion",
	"Courthouse",
	"Steak",
	"Politician",
	"Car Wash",
	"Soup",
	"Toilet",
	"Stranger",
	"Chainsaw",
	"Firecracker",
	"Shower Head",
	"Therapist",
	"Sucker Punch",
	"Surprise",
	"Refrigerator",
	"School Bus",
	"Bellboy",
	"Deadline",
	"Wheelbarrow",
	"Stroke",
	"Heart Attack",
	"Fluke",
	"Dog Walker",
	"Good-Bye",
	"Hammer",
	"Signature",
	"Disaster",
	"Sneeze",
	"Preference",
	"Suggestion",
	"Mailbox",
	"Lunch",
	"Dinner",
	"Breakfast",
	"Whip",
	"Semi-Truck",
	"Gut-Puncher",
	"Temptation",
	"Tongue-Twister",
	"Terror",
	"Outhouse",
	"Square Dance",
	"Judge",
	"Taxpayer",
	"Lobster",
	"Machine",
	"Gravy",
	"Christmas",
	"Drink",
	"Handshake",
	"Probe",
	"Hazard",
	"Funeral",
	"Swing",
	"Club",
	"Linebacker",
	"Sludge",
	"Exit",
	"Solution",
	"Sucker Punch",

]

const quips = [

	"Hey, that looks pretty good to me.",
	"Not my best work, but whatever.",
	"It was my mother's recipe.",
	"Enjoy, I guess.",
	"Time to party.",
	"You're welcome, idiot.",
	"The secret ingredient is hate.",
	"Drink it. I dare you.",
	"How many ounces are in a liter?",
	"I'm bored.",
	"They should make Top Chef, but for bartending. Call it Top Bar.",
	"Mixology isn't a real profession.",
	"Your liver will thank me.",
	"Time to meet your maker.",
	"Alcoholism, meet my good friend, alcohol.",
	"Your liver has met its match.",
	"I probably wouldn't drink that.",
	"I'm 97.3352% sure you'll like this",
	"This was Coolio's favorite drink.",
	"There might be some broken glass in there.",
	"If you're a cop, you have to tell me.",
	"Science says you'll like this. Or else.",
	"Don't drink this one if you're allergic to peanuts.",
	"Try not to think too much about what's in it.",
	"This is a drink, that's all I can say.",
	"Instant classic.",
	"Do you have a life insurance policy? Asking for a friend.",
	"It's ok, not great.",
	"I'll give you five bucks to drink this.",
	"It's probably fine.",
	"Don't let looks deceive you. It's probably fine.",
	"It would be a crime NOT to drink this.",
	"I plead the fifth.",
	"It tastes good, I promise.",
	"Bottoms up.",
	"Smells like home cookin'",
	"This is a crime against taste buds.",
	"I'm actually pretty proud of this one.",
	"The less you know, the better",
	"I'm getting really tired of making drinks.",
	"I'm just making things up as I go along here.",
	"I'm running out of ideas.",
	"9 out of 10 doctors reccomend you to drink this and stop asking quesitons.",
	"Drink this, just not too much of it.",
	"This is safe to drink.",
	"I'm so sick of coming up with this stuff.",
	"This recipe was passed down from my Motherboard to me.",
	"Don't worry, the EMT's are on their way. Probably.",

]